### PR TITLE
Reorganize abstracts & interfaces

### PR DESCRIPTION
**Pull request by borkweb**
- Reorganized abstract classes and interfaces into `Contracts/` directories. (I like that approach from Give)
- Switched away from `StellarWP\Schema\Container` in favor of using `lucatume\DI52\App` and `lucatume\DI52\Container`.

This builds on top of #5 with the intent of being part of `1.1.0`.

**Addresses:** #8 and #9

### CODE REVIEW

**Review by lucatume — APPROVED** [review]

**Comment by JasonTheAdams** [comment]
@borkweb Rather than introducing a new package and container in multiple packages, I'm inclined to make it possible within package configuration for the implementing plugin to provide its own PSR-11 compatible service container instance — which is then used by the package. What do you think?

**Comment by JasonTheAdams** [comment]
Man, that PSR-11 interface sucks more than I realized. It's way too limited. It doesn't even have the ability to set items within the container, much less singletons. We may consider making our own StellarWP/Container package that's, at the very least, our own interface.

**Comment by borkweb** [comment]
@JasonTheAdams - I agree that it'd be great to provide a way to inject a container. That being said, I'd love this library to provide a sensible default for those that do not have the desire or knowledge of how to provide a container. We definitely need to have a more lengthy conversation around this topic with some more folks.

**Comment by JasonTheAdams** [comment]
I guess that depends on the assumptions we're willing to make. If we include this as a default for every package that uses a Container, then that's increasing the size of that package (and plugin) by ~1 MB/plugin — assuming this PR gets merged and it's not 50 MB: https://github.com/lucatume/di52/pull/39 😬

**Comment by borkweb** [comment]
Switching this back to draft mode because #14 rethinks some of the foundational elements that these changes build on.

**Comment by borkweb** [comment]
Alrighty, with the addition of a `Config` class for Container and DB objects, this PR is now solely about relocating the interfaces and abstracts.

**Pull request merged**
