### PR TITLE
Normalize Composer configuration against the Composer schema

### PR DESCRIPTION
**Pull request by szepeviktor**
There is a Composer plugin called `ergebnis/composer-normalize`.

### CODE REVIEW

**Comment by szepeviktor** [comment]
@borkweb Conflict resolved.

**Review by borkweb — APPROVED** [review]
Nice! I had no idea that composer plugin was a thing. Pretty awesome. I now have that installed globally on my machine. 🕺 Thank you for the tip!

**Comment by borkweb** [comment]
Just tested this out and it composer installs fine (as expected). Merging.

**Comment by szepeviktor** [comment]
Because there is manual change in this PR.

**Pull request merged**
